name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Install Dependencies
        run: yarn install

      - name: Build Dist
        run: yarn build

      - name: Setup git config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
      
      - name: Commit
        run: |
          git add dist
          git commit -m "[actions] updated dist with the latest"
          git push origin master
